"""empty message

Revision ID: 1215f82f8bfc
Revises: 
Create Date: 2018-06-25 22:00:17.041761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1215f82f8bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AcademicStates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('repeating', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('correlative', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=2), nullable=True),
    sa.Column('lective_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('students.id', sa.Integer(), nullable=False),
    sa.Column('subject.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['students.id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject.id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('students.id', 'subject.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('users')
    op.drop_table('subject')
    op.drop_table('students')
    op.drop_table('AcademicStates')
    # ### end Alembic commands ###
