# Generated by Django 3.1.3 on 2020-11-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duckname', models.CharField(max_length=255)),
                ('ducklastname', models.CharField(max_length=255)),
                ('duckmail', models.EmailField(max_length=255)),
                ('duckage', models.IntegerField()),
            ],
        ),
    ]
